


# model specific
model : "deterministic"
resume : ""
arch : "resnet50"
pool : "gem"
whitening : True
pretrained : True
latent_dim : 512
type_of_triplets : "hard"

# logging
log_dir : "../results"
check_val_every_n_epoch : 1

# training
train : True
epochs : 20
lr : 3.0e-7
loss : "bayesian"
margin : 1
distance : "euclidean"
varPrior : 0.01
distribution : "gauss"
kl_scale_factor : 1e-6

# data specific
data_dir : "/content/data"
dataset : "cub200"
batch_size : 64
split_query_database : False
